In [2]:
import torch

In [3]:
#Tensor with passing values
t1 = torch.tensor([1,2,3])
t1

tensor([1, 2, 3])

In [5]:
# Tensor of zero's no. of rows, col
zero = torch.zeros(5,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#Tensor of one's with no.of row,col
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# Create a random tensor
random_tensor = torch.rand(size=(3, 4)) # this will create a tensor of size 3x4 but you can manipulate the shape however you want
random_tensor

tensor([[0.1837, 0.8000, 0.4710, 0.7358],
        [0.9947, 0.3715, 0.9964, 0.9130],
        [0.9682, 0.9761, 0.1381, 0.5243]])

In [9]:
a = torch.rand(3,2)
b = torch.rand(2,4)
a

tensor([[0.1890, 0.9370],
        [0.8062, 0.8358],
        [0.6301, 0.6363]])

In [10]:
b

tensor([[0.7310, 0.7619, 0.4557, 0.8180],
        [0.1336, 0.8598, 0.4725, 0.0978]])

In [11]:
#matrix multiplication
matmul = torch.matmul(a,b)
matmul

tensor([[0.2633, 0.9497, 0.5289, 0.2463],
        [0.7010, 1.3329, 0.7623, 0.7413],
        [0.5456, 1.0272, 0.5878, 0.5777]])

In [13]:
# Matrix multiplication (element-wise multiplication)
mm = torch.mm(a,b)
mm

tensor([[0.2633, 0.9497, 0.5289, 0.2463],
        [0.7010, 1.3329, 0.7623, 0.7413],
        [0.5456, 1.0272, 0.5878, 0.5777]])